.TH CIDR 1
.SH NAME
cidr \- RFC 1878 subnet helper
.SH SYNOPSIS
.TP
.B cidr [\-v]
.TP
.B cidr <ipaddress> <subnetmask>
.TP
.B cidr <ipaddress/prefix>
.SH DESCRIPTION
.B cidr
is a utility for determining the network address and broadcast address
for a CIDR subnet.  It takes as input an ip address and netmask or 
and ip/prefix combination.  It outputs the network address, broadcast
address, wildcard address and a network size count.
.SH OPTIONS
.TP
.B \-v
print version information
.TP
.B "<ipaddress> <subnetmask>"
IP address will full subnet mask expansion ie. 203.0.113.0 255.255.255.0
.TP
.B "<ipaddress/prefix>"
IP address as an ip/cidr combination ie. 203.0.113.0/24
.SH EXAMPLES

cidr 198.51.100.0/28

cidr 198.51.100.0 255.255.255.240

.SH COPYRIGHT
cidr.c -- determine CIDR network and broadcast address from
IPv4 ip address and netmask

Heavily Modified October 2015 Stephen Rozanc
Copyright Original (C) 2000 Robert L. Lineberger 

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

.SH AUTHOR
Stephen Rozanc <github.com/krallice>
.SH CONTRIBUTORS
Robert L. Lineberger <robert@geeksoul.com>

David A. Bandel

Iain Lea

Herman Robers
.SH SEE ALSO
RFC 1878
